#define bon }
#define finche while
#define fa {
#define se if 
#define senno else
#define ciapaqua return
#define e_anca &&
#define oppur ||
#define sito_mato !
#define numero int
#define vero true
#define falso false
#define scrivi std::cout
#define leggi std::cin
#define programma int main() 
#define fine }
#define virgola float
#define argomenti (
#define ebasta )
#define controea switch 
#define se_xe case
#define fermite break;
#define acapo std::endl;
#define altrimenti default
#define vanti_col_lavor continue;
#define par_ogni for
#define caratere char
#define paco_de_roba struct
#define gnente void
#define beo_longo long long
#define beo_corto short
#define beo_preciso double
#define vero_falso bool
#define vero true
#define mia_vero false
#define sempre_queo const
#define sempre_quel const
#define no_cambia const
#define sempre_quea const
#define frase std::string
#define scrivi_su_file std::ofstream
#define scrivi_negli_inferi std::cerr
#define sensa_argomenti ()
#define sta_qua static
#define zontighe +=